---
title: 'Unix/Shell & AWS Instances'
author: "Taylor Darby"
date: "11/10/2021"
output: pdf_document
---

# Learning Shell

## Commands for shell can be typed directly into the Terminal tab in R.

### Code Key:

pwd = current path "print working directory"
cd = change directory
ls = list everything in directory
mkdir = make directory
rm = remove files
rmdir = remove directory
touch = create file
nano = basic text file editor (Note: to exit out of nano hit "Ctrl" + "X", then "Y", then "Enter")
cp = copy (the first value is the source and the second value is the destination)
less = summary of file ("q" to exit out of "less")
mv = move a file or change the name of a file (the first value is the source and the second value is the destination)
man = manual
head = beginning of file
tail = end of file
grep = prints lines that match patterns


### Notes:

**absolute paths** are more resilient because they access the specified directory/file not matter what current directory you're currently in. absolute paths start with a "/"

**relative paths** only work if the specified directory/file is downstream of whatever directory you are currently in

**FOR EMERGENCY QUIT:** "esc" then ":q!"

**ls -l** will list contents in a different way

**asterisks** perform specified command on any contents with a name containing what's within the asterisks (i.e. "ls protein*" will list anything that starts with "protein")

**Pause a job** my calling "^Z" then start it again using "fg" or run it in the background using "bg"

# Amazon Web Services: Launching AWS Instances

## Accessing the AWS console

Went to this website to access AWS:  https://awsed.ucsd.edu/

Clicked "Launch Instances" to open new instance

Step 1. Choose 64-bit Ubantu Server 20.04 AMI.

Step 2. Choose "m5.2xlarge" instance.

Skip to step 6 usually

Step 6. Choose "Select existing security group" and select BGGN213

Step 7. Review warnings and settings before accepting charges and launching.

Launch

Note: SSH login requires your login. Create a new key pair will generate this login.

Today I generated a new key pair using the key pair name: "bioinformatics_tdarby". Downloaded the key then launched. The instance i-00d9d1750560b77dc launch was initiated. I can access this instance via this IP:  ec2-35-85-45-79.us-west-2.compute.amazonaws.com

## 1. Logging in to an AWS instance from your local terminal

In Rstudio terminal we can access this instance using:

**cd into directory containing .pem file**

**chmod 400 bioinformatics_tdarby.pem**

**ssh -i bioinformatics_tdarby.pem unubtu@ec2-35-85-45-79.us-west-2.compute.amazonaws.com**

You can double check you are logged in using the code "whoami"

## 2. Update the software on the machine

Use the following code to update your software:

**sudo apt-get update**  
**sudo apt-get -y install ncbi-blast+**

## 3. Download some sequences to work with

### Created a directory called "work". Within "work" we did this:

Downloaded files from NCBI using:

**curl -O ftp://ftp.ncbi.nih.gov/refseq/M_musculus/mRNA_Prot/mouse.1.protein.faa.gz**

**curl -O ftp://ftp.ncbi.nih.gov/refseq/M_musculus/mRNA_Prot/mouse.2.protein.faa.gz**

**curl -O ftp://ftp.ncbi.nih.gov/refseq/D_rerio/mRNA_Prot/zebrafish.1.protein.faa.gz**


## 4. Inspect our sequences

These are zipped files. We unzipped them using "gunzip *.faa.gz" which unzips anything ending in ".faa.gz".

**Q1.** What does the star character accomplish here?

### Asterisks perform specified command on any contents with a name containing what's within the asterisks (i.e. "ls protein*" will list anything that starts with "protein")

**Q2.** How many sequences are in this mouse.1.protein.faa file?

Looked for occurrence of ">" within a file using: grep -c ">" mouse.1.protein.faa

### There are 67941 sequences.

Checked out the beginning of the mouse file using: head mouse.1.protein.faa

Saved the first 11 lines of the zebrafish file to a new file using: head -11 mouse.1.protein.faa > mm-first.fa

**Q3.** What happens if you run the above command without the > mm-first.fa part?

### It will just print out the beginning of the contents of the mouse file.

**Q4.** What happens if you were to use two ‘>’ symbols (i.e. >> mm-first.fa)?

### ">>" will overwrite data within the file

Built a new database using: makeblastdb -in zebrafish.1.protein.faa -dbtype prot

## 5. Running our first command line BLAST

Ran a query search using: blastp -query mm-first.fa -db zebrafish.1.protein.faa

Ran a second query search using: head -497 mouse.1.protein.faa > mm-second.fa

## 6. Running more BLAST jobs

Compared the first 80 sequences using: blastp -query mm-second.fa -db zebrafish.1.protein.faa -out mm-second.x.zebrafish.txt

**Q5.** How would you determine how many sequences are in the mm-second.fa file?

### grep -c ">" mm-second.fa determines there are 83 sequences

## 7. Producing a TSV output

Generated a tabular file using: blastp -query mm-second.fa -db zebrafish.1.protein.faa -out mm-second.x.zebrafish.tsv -outfmt 6

## 8. Transfer your results back to your computer

Created a new terminal and now working on local computer

This is how you pull a file from your AWS onto your local environment to work with in Rstudio: 

scp -i ~/Desktop/SDSU/UCSD/BGGN213/unix_shell/bioinformatics_tdarby.pem ubuntu@ec2-35-86-165-28.us-west-2.compute.amazonaws.com:/home/ubuntu/work/mm-second.x.zebrafish.tsv .


